#!/bin/sh

ESLINT_EXTS=\{js,jsx,mjs\}
ESLINT_EXTRAS=( jest.config.js postcss.config.js )
SRC_DIRS=\{config,jest,scripts,src,styleguide,utils\}

./node_modules/.bin/eslint $SRC_DIRS/**/*.$ESLINT_EXTS ${ESLINT_EXTRAS[@]}
